defaults:
  - base_config
  - system_config
  - support_config/mobility_config@_here_
  - _self_

# ============================================================
# ROS CONFIG
# ============================================================
# Frequency of the main ROS loop (Hz)
# Controls how many times per second spin() calls run_once()
ros_rate: 15

# Path to ROS topic configuration file
ros_stream_config_path: ./config/data_config/ros/self_collected.yaml

# If RGB & Depth topics are published as compressed image topics, set to true
# If false, topics are expected to be raw image topics
use_compressed_topic: false

# Maximum allowed time difference (in seconds) between synchronized topics
sync_threshold: 0.1


# ============================================================
# DUALMAP CONFIG
# ============================================================
## Detection Config
# Enable object detection during mapping
# 在建图的时候是否启用物体检测
run_detection: True

# Show detection results on Rerun during runtime
# 在运行的时候是否在Rerun上显示检测结果
visualize_detection: True

# Use FastSAM for Open-Voca supplementation
# 使用FastSam进行开放词汇的补充检测
use_fastsam: False

# Detection Refinement
# skip refinement will be faster but less accurate
skip_refinement: false

## Visualization
# Enable Rerun visualization
use_rerun: True
# Enable Rviz visualization
use_rviz: False

## Parallelization
# Use parallel processing (False = sequential)
use_parallel: true


# ============================================================
# SYSTEM MAPPING CONFIG
# ============================================================
# If True, run local mapping only and get local map
# If False, run both local and global mapping and get global map
run_local_mapping_only: false

# Save the generated local map
save_local_map: false

# Save the global map (set False if run_local_mapping_only is True)
save_global_map: true


# ============================================================
# PRELOADING CONFIG
# ============================================================
# Preload an existing global map from disk
preload_global_map: false

# Preload an existing layout pcd and wall pcd from disk
# If preload the layout, the layout pcd thread will be disabled
preload_layout: false

# Path to preload map data.
# If empty, the system will use the default preload path
# preload_path: ""
# preload_path: "dataset/HM3D_collect/00829-QaLdnwvtxbs/global_map/hm3d"
preload_path: "output/map_results/hm3d_00829-QaLdnwvtxbs/session_hm3d_00829-QaLdnwvtxbs_20251128_161656"

# Preload action paths for visualization
use_given_path: false
given_path_dir: ""